<?php

CONST IN_DEBUG_MODE = false;

// General Settings
CONST DPO_VENDOR = 'DPO VENDOR NAME';
CONST SALT = 'SALT TO HASH PASSWORDS';
CONST NVS_DAYS = 3650;
CONST ALLOWED_UPDATES = 2;
CONST SEARCH_DEPTH = 10;

// Emercoin RPC Settings
CONST RPC_TYPE = "https";
CONST RPC_USERNAME = "USERNAME";
CONST RPC_PASSWORD = "PASSWORD";
CONST RPC_HOST = "HOSTNAME";
CONST RPC_PORT = '6662';

// Vendor Variables
CONST NAME = 'Name';
CONST LOGO = 'Logo';

// Product Variables
CONST SIGNATURE = 'Signature';
CONST COMMENT = 'Comment';
CONST OWNER = 'Owner';
CONST SECRET = 'Secret';
CONST OTP = 'OTP';
CONST UPDATED = 'Updated';
CONST PHOTO = 'Photo';
CONST ITEM = 'Item';
