<?php
const DPO_VENDOR = 'DPO VENDOR NAME';
const SALT = 'SALT TO HASH PASSWORDS';
const NVS_DAYS = 10;

// http or https
CONST RPC_TYPE = "https";
CONST RPC_USERNAME = "USENAME";
CONST RPC_PASSWORD = "PASSWORD";
CONST RPC_HOST = "HOSTNAME";
CONST RPC_PORT = '6662';

CONST ALLOWED_UPDATES = 10;
CONST SEARCH_DEPTH = 10;
CONST BASE_URL = '';

CONST SIGNATURE = 'Signature';
CONST COMMENT = 'Comment';
CONST OWNER = 'Owner';
CONST SECRET = 'Secret';
CONST OTP = 'OTP';
CONST UPDATED = 'Updated';
CONST NAME = 'Name';
CONST PHOTO = 'Photo';
CONST ITEM = 'Item';
CONST LOGO = 'Logo';

